// Restores a daily backup JSON (produced by api/backup-export.js) into a
// Postgres/Supabase database, table by table, in foreign-key dependency
// order. Companion to supabase/RESTORE_PROCEDURE.md -- read that first,
// this is the "do it" half of the documented restore procedure, not a
// replacement for understanding what it's doing before you run it
// against anything that matters.
//
// What this does NOT do, on purpose: it does not touch Storage bucket
// contents (attachments), does not restore the four tables whose
// credential columns are stripped before export (see below -- those need
// to be reconnected/regenerated by hand afterward, same as the export
// itself documents), and does not run any schema migration -- the target
// database needs the current supabase/schema*.sql files already applied
// before this script runs, same order as SETUP.md section 1.
//
// Usage:
//   SUPABASE_URL=... SUPABASE_SERVICE_ROLE_KEY=... \
//     node scripts/restore-backup.js path/to/pipeline-backup-2026-08-27.json [--dry-run]
//
// --dry-run prints what would be inserted (table names + row counts, in
// the order they'd run) without writing anything -- use this first,
// always, especially the first time you ever run this for real.
//
// Every table restore uses upsert (insert ... on conflict (id) do
// update) rather than a bare insert, so re-running this script after a
// partial failure is safe -- it won't throw on rows that already made it
// in on a previous attempt.
import { readFileSync } from 'node:fs'
import { createClient } from '@supabase/supabase-js'

// Same dependency order api/backup-export.js's tables need to be
// re-inserted in, derived from every `references public.<table>` in
// supabase/schema*.sql (parents before children). Tables not listed here
// but present in a backup file (schema drift between when the backup was
// taken and when this script was last updated) are restored last, in
// whatever order the backup file has them, with a warning -- better than
// silently dropping them.
const RESTORE_ORDER = [
  'profiles',
  'organizations',
  'org_members',
  'projects',
  'tasks',
  'activity_log',
  'attachments',
  'calendar_events',
  'chat_conversations',
  'chat_conversation_participants',
  'chat_messages',
  'chat_message_mentions',
  'chat_conversation_reads',
  'clients',
  'google_calendar_connections',
  'calendar_event_google_links',
  'invoices',
  'invoice_items',
  'mfa_backup_codes',
  'notification_preferences',
  'project_assignees',
  'notifications',
  'recurring_invoice_templates',
  'recurring_invoice_items',
  'stripe_connections',
  'stripe_events',
  'task_assignees',
  'task_comments',
  'task_relations',
  'task_templates',
  'task_template_items',
  'task_activity_log',
  'tickets',
  'ticket_comments',
  'wise_reconciliation_connections',
  'wise_transactions',
]

// Mirrors api/backup-export.js's SENSITIVE_COLUMNS -- these columns were
// stripped before export, so they simply won't be present on the rows
// below. Listed here only so the summary output can remind you what
// needs reconnecting/regenerating by hand after the restore finishes.
const STRIPPED_CREDENTIALS = [
  'google_calendar_connections (refresh_token, access_token) — reconnect Google Calendar per org/user',
  'wise_reconciliation_connections (api_token) — reconnect Wise per org',
  'stripe_connections (secret_key, webhook_secret) — reconnect Stripe per org',
  'mfa_backup_codes (salt, code_hash) — every user regenerates backup codes from Settings',
]

const PAGE_SIZE = 500

async function main() {
  const [, , filePath, ...flags] = process.argv
  const dryRun = flags.includes('--dry-run')

  if (!filePath) {
    console.error('Usage: node scripts/restore-backup.js <backup.json> [--dry-run]')
    process.exit(1)
  }

  const supabaseUrl = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY
  if (!dryRun && (!supabaseUrl || !serviceRoleKey)) {
    console.error('SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY must be set (skip this check with --dry-run).')
    process.exit(1)
  }

  const raw = JSON.parse(readFileSync(filePath, 'utf8'))
  const tables = raw.tables || {}
  console.log(`Backup exported_at: ${raw.exported_at}`)
  console.log(`Tables present in file: ${Object.keys(tables).length}\n`)

  const orderedNames = [...RESTORE_ORDER.filter((t) => tables[t]), ...Object.keys(tables).filter((t) => !RESTORE_ORDER.includes(t))]
  const unknown = orderedNames.filter((t) => !RESTORE_ORDER.includes(t))
  if (unknown.length) {
    console.warn(`WARNING: ${unknown.length} table(s) in the backup aren't in this script's known order (schema has changed since this script was last updated): ${unknown.join(', ')}. They'll be restored last, unordered — verify manually that's safe.\n`)
  }

  if (dryRun) {
    console.log('--dry-run: no writes will be made. Restore order:\n')
    for (const name of orderedNames) {
      console.log(`  ${name.padEnd(35)} ${tables[name].length} rows`)
    }
    console.log('\nCredential columns NOT in this backup (reconnect/regenerate after a real restore):')
    for (const line of STRIPPED_CREDENTIALS) console.log(`  - ${line}`)
    return
  }

  const admin = createClient(supabaseUrl, serviceRoleKey, {
    auth: { autoRefreshToken: false, persistSession: false },
  })

  const summary = []
  for (const name of orderedNames) {
    const rows = tables[name]
    if (!rows || rows.length === 0) {
      summary.push({ table: name, rows: 0, status: 'skipped (empty)' })
      continue
    }
    let restored = 0
    let failed = null
    for (let i = 0; i < rows.length; i += PAGE_SIZE) {
      const chunk = rows.slice(i, i + PAGE_SIZE)
      const { error } = await admin.from(name).upsert(chunk, { onConflict: 'id' })
      if (error) {
        failed = error.message
        break
      }
      restored += chunk.length
    }
    summary.push({ table: name, rows: restored, status: failed ? `FAILED: ${failed}` : 'ok' })
    console.log(`${name.padEnd(35)} ${failed ? 'FAILED' : `${restored}/${rows.length} rows`}`)
    if (failed) {
      console.error(`  -> stopping here. Fix the error above, then re-run this script (upsert makes it safe to resume).`)
      break
    }
  }

  console.log('\n--- Restore summary ---')
  for (const s of summary) console.log(`  ${s.table.padEnd(35)} ${s.status}`)

  console.log('\n--- Manual follow-up required ---')
  for (const line of STRIPPED_CREDENTIALS) console.log(`  - ${line}`)
  console.log('  - Verify RLS is still enabled on every table (it lives in schema, not in the data, but confirm after any fresh-project restore)')
  console.log('  - See supabase/RESTORE_PROCEDURE.md for the full post-restore checklist')
}

main().catch((err) => {
  console.error('Restore failed:', err)
  process.exit(1)
})
